project: https://github.com/qualcomm/sensinghub

branches:
  main:
    modes:
      non-blocking:
        headers:
          - common/inc/*.h
          - session/1.0/inc/*.h
          - utils/inc/*.h

abi_checks:
  - path: build/usr/lib
    include_globs:
      - libsensinghubapi.so
      - libsensinghubsession.so
      - libqshUtil.so