name: Qualcomm Preflight Checks

on:
  pull_request_target:
    branches: [ main , dev , dev-axiom ]
  push:
    branches: [ main , dev , dev-axiom]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  qcom-preflight-checks:
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/qcom-preflight-checks-reusable-workflow.yml@v1.1.4
    with:
      # ✅ Preflight Checkers
      repolinter: true
      semgrep: true
      copyright-license-detector: true
      pr-check-emails: true
      dependency-review: true
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
